name: flutterapp
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"
  
dependencies:
  flutter:
    sdk: flutter
  csv: ^6.0.0
  path_provider: ^2.0.0
  flutter_slidable: ^3.1.0
  qr_flutter: ^4.1.0
  image_picker: ^1.0.0
  file_picker: ^8.1.2
  shared_preferences: ^2.2.2
  http: ^1.2.2
  cupertino_icons: ^1.0.8
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  share_plus: ^10.1.3   
  image: ^4.2.0

 
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logotipo_firma.png